### PR TITLE
Merge 2.6 into master

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/151)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[build/Ionic.Zip.dll, line 0 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DOloE5mCeic-j1fvy:-L-DOloE5mCeic-j1fvz:b90ee0h) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/build/Ionic.Zip.dll#L0)):*
I think this should be deleted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Comment by jasonleenaylor** [comment]
*[build/MSBuild.ExtensionPack.dll, line 0 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DOz2y4wzlhqsJz4f3:-L-DOz2y4wzlhqsJz4f4:b-6ir511) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/build/MSBuild.ExtensionPack.dll#L0)):*
This should be deleted too, if it isn't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Comment by papeh** [comment]
Review status: 0 of 55 files reviewed at latest revision, 2 unresolved discussions.

---

*[build/Ionic.Zip.dll, line  at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DOloE5mCeic-j1fvy:-L-DPeTmoQzIBeCozsWa:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/build/Ionic.Zip.dll#L)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I think this should be deleted
</blockquote></details>

Done.

---

*[build/MSBuild.ExtensionPack.dll, line  at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DOz2y4wzlhqsJz4f3:-L-DPerPavokTnUCWZSK:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/build/MSBuild.ExtensionPack.dll#L)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This should be deleted too, if it isn't
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Comment by jasonleenaylor** [comment]
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DReddtJJzmvMvwCRj:-L-DReddtJJzmvMvwCRk:b2nhdq2) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L7)):*
> ```Smalltalk
> using SIL.TestUtilities;
> using Chorus.Model;
> using Chorus.Model;
> ```

Dup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Comment by jasonleenaylor** [comment]
Reviewed 55 of 55 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Comment by jasonleenaylor** [comment]
One duplicated using to clean up either here or in a follow up. :LGTM:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151#-:-L-DRqD_-1pT_mxvqbal:byldfqh)*

**Comment by papeh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/151#-L-DReddtJJzmvMvwCRj:-L-DSSQEugJMjbVexMi1:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/b1bdad5fa02126a093973ecb46b8a1e691cd1454/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L7)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Dup
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/151)*

**Pull request merged**
