### PR TITLE
Nugetification of chorus 2.5

### PR DESCRIPTION
**Pull request by glasseyes**
Use nuget to get dlls instead of storing ones of different versions in the repos
I'll do the same for master in a separate PR once it is working again

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/139)

### CODE REVIEW

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-KvayAUhFXqnMZyS5nOD:bnfp4nl)*

**Comment by papeh** [comment]
One gotcha: Since you are now downloading Build Extensions a build task, the build will need to run twice on a clean machine before it succeeds. (To solve this problem on the build server, add a build step to download the tasks (`msbuild /t:RestoreNuGet` or similar) before running the existing build task(s).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-KvdSyrgh5L7JoTvBeJV:b-mhows0)*

**Comment by glasseyes** [comment]
Good catch Hasso, I'd missed adding the package to .nuget/packages.config. The build shouldn't need to run twice now

---

Review status: 22 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-KveWFxHFQ8Lt8_vlOAW:b-14ptqr)*

**Comment by papeh** [comment]
I hadn't noticed the missing package from packages.config either. The build will still need to run twice on a clean machine. (To allow developers to build in one command, make a shell or batch script to restore packages before running the main build.) Otherwise, :LGTM:

---

Reviewed 22 of 23 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-KvnIoHkapQ0_d16Yb4m:bxnkt9i)*

**Comment by glasseyes** [comment]
Hasso, are you sure about this? When I've started with a clean repo I can build just fine from the command line without manually restoring the packages. In the PR I moved the import of NuGet.targets to before the needed packages are used - so it gets them before they are used.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-Kvyx4OHwFfWaETnXnSq:b16hlh9)*

**Comment by ermshiperete** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139)*

**Comment by papeh** [comment]
interesting.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-Kw0Mw6uwFLbCTbmC-qm:b-ouq6yt)*

**Comment by papeh** [comment]
So you removed your packages directory and rebuilt correctly the first time? If that doesn't work, please add the necessary build step to each affected configuration on TeamCity.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/139#-:-Kw0c88wL2vMwUQcJmgG:bm0ixqm)*

**Pull request merged**
