### PR TITLE
LT-18674 Update to 0.13_ldml3 chorus branch on ldml v3 projects

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* Adjust GetBranchNameFromLiftFile to append _ldml3.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/143)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by sillsdevgerrit** [comment]
Can one of the admins verify this patch?

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/143#-:-KyICjsBXGjEhB8wYKVy:bnfp4nl)*

**Comment by papeh** [comment]
Reviewed 2 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/Chorus.proj, line 120 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/143#-Kyr2PHX24BPJYxAU7I-:-Kyr2PHX24BPJYxAU7I0:b-v35fjp) ([raw file](https://github.com/sillsdev/chorus/blob/98dc42fea42fb8b95e3e8ba47d0f0a79f1649a71/build/Chorus.proj#L120)):*
> ```XML
> 		</PropertyGroup>
> 		<ItemGroup>
> 			<TestAssemblies Include="$(RootDir)/output/$(Configuration)/*.Tests.dll" Exclude="$(RootDir)/output/$(Configuration)/SIL.WritingSystems.Tests.dll"/>
> ```

Good job finding all the places that need to change!

---

*[src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs, line 13 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/143#-Kyr6ii_8Dj_7Bv3Kfcn:-Kyr6ii_8Dj_7Bv3Kfco:bgon7ds) ([raw file](https://github.com/sillsdev/chorus/blob/98dc42fea42fb8b95e3e8ba47d0f0a79f1649a71/src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs#L13)):*
> ```Smalltalk
> 	public class LiftSynchronizerAdjunctTests
> 	{
> 		private const string testLift13File =
> ```

case should be `TestLift13File`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/143)*

**Comment by RaymondLuong3** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/Chorus.proj, line 120 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/143#-Kyr2PHX24BPJYxAU7I-:-KyvaU3S4Twh-E9Q1W3k:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/98dc42fea42fb8b95e3e8ba47d0f0a79f1649a71/build/Chorus.proj#L120)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Good job finding all the places that need to change!
</blockquote></details>

Done.

---

*[src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs, line 13 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/143#-Kyr6ii_8Dj_7Bv3Kfcn:-KyvaLxMX1_VZWfp2WEB:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/98dc42fea42fb8b95e3e8ba47d0f0a79f1649a71/src/LibChorusTests/FileHandlers/Lift/LiftSynchronizerAdjunctTests.cs#L13)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

case should be `TestLift13File`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/143)*

**Comment by jasonleenaylor** [comment]
Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/143)*

**Pull request merged**
