### PR TITLE
Internet Dialog Improvement

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[src/LibChorus/VcsDrivers/RepositoryAddress.cs, line 146 at r1](https://reviewable.io/reviews/sillsdev/chorus/223#-MK1a3H468HzDIS2igP9:-MK1a3H468HzDIS2igPA:bdy1xhz) ([raw file](https://github.com/sillsdev/chorus/blob/a2a9e2b9e22e6b63e6a1563b519484796ef2b852/src/LibChorus/VcsDrivers/RepositoryAddress.cs#L146)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 		//public string Password
> 		//{
> 		//	get { return UrlHelper.GetPassword(URI); }
> 		//}
> 		//public string UserName
> 		//{
> 		//	get { return UrlHelper.GetUserName(URI); }
> 		//}
> ```
</details>

I don't think you need these anymore.

**Comment by jasonleenaylor** [comment]
___
*[src/LibChorus/VcsDrivers/RepositoryAddress.cs, line 180 at r1](https://reviewable.io/reviews/sillsdev/chorus/223#-MK1gRUt8gUuq3SB8yl0:-MK1gRUu1VZhHtAqY9oW:b-pzedza) ([raw file](https://github.com/sillsdev/chorus/blob/a2a9e2b9e22e6b63e6a1563b519484796ef2b852/src/LibChorus/VcsDrivers/RepositoryAddress.cs#L180)):*
> ```
> public HttpRepositoryPath(string a, string b, bool c) : this(a, b, c, "user", "ao") { }
> ```
Well this is ... interesting. :smile:

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/LibChorus/VcsDrivers/RepositoryAddress.cs, line 180 at r1](https://reviewable.io/reviews/sillsdev/chorus/223#-MK1gRUt8gUuq3SB8yl0:-MK5RKEt2lmklScSvXZC:b-kf048i) ([raw file](https://github.com/sillsdev/chorus/blob/a2a9e2b9e22e6b63e6a1563b519484796ef2b852/src/LibChorus/VcsDrivers/RepositoryAddress.cs#L180)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> public HttpRepositoryPath(string a, string b, bool c) : this(a, b, c, "user", "ao") { }
> ```
Well this is ... interesting. :smile:
</blockquote></details>

I'd like to drop this constructor, but  it's used in tests and the smart RepositoryAddress.Create() method. Maybe I'll default to username = password = null.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 17 of 21 files at r3, 2 of 2 files at r4, 6 of 6 files at r5, 19 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: all files reviewed, 1 unresolved discussion (waiting on @papeh)

___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 247 at r6](https://reviewable.io/reviews/sillsdev/chorus/223#-MR1HGeAAkDMeryRJfOU:-MR1HGeAAkDMeryRJfOV:b-45ep9o) ([raw file](https://github.com/sillsdev/chorus/blob/36e91aa6d85285b6ee1dbf4ff3018bd784558181/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L247)):*
> ```
> // TODO ??:Assert.A
> ```
So is this returning Low Bandwidth right now?

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 5 files at r7, 3 of 5 files at r8, 2 of 2 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

___
*[src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs, line 35 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6W4NOAK_bY7G60iZa:-MR6W4NP7Wmigj8zgqqE:b1h4vi) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs#L35)):*
> ```
> 				Assert.AreEqual("account", model.Username);
> 				Assert.AreEqual("password", model.Password);
> ```
barring difficult to imagine side effects these asserts seem pointless
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 247 at r6](https://reviewable.io/reviews/sillsdev/chorus/223#-MR1HGeAAkDMeryRJfOU:-MR6WQBi7SgTt4d0uT35:bnfp4nl) ([raw file](https://github.com/sillsdev/chorus/blob/36e91aa6d85285b6ee1dbf4ff3018bd784558181/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L247)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> // TODO ??:Assert.A
> ```
So is this returning Low Bandwidth right now?

</blockquote></details>

:lgtm:

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)

___
*[src/LibChorus/Model/ServerSettingsModel.cs, line 214 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6ruv40E6uCwhtoZQg:-MR6ruv40E6uCwhtoZQh:b9bsc4y) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorus/Model/ServerSettingsModel.cs#L214)):*
> ```Smalltalk
> 		private WebResponse LogIn()
> 		{
> 			var request = WebRequest.Create($"https://admin.languageforge.org/api/user/{Username}/projects");
> ```

this doesn't list private projects; I don't know where to call for that, but hopefully users know their project names :thinking: 
___
*[src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs, line 35 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6W4NOAK_bY7G60iZa:-MR6vff_A_nmfjzCCEla:bweihd7) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorusTests/Model/InternetCloneSettingsModelTests.cs#L35)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> 				Assert.AreEqual("account", model.Username);
> 				Assert.AreEqual("password", model.Password);
> ```
barring difficult to imagine side effects these asserts seem pointless
</blockquote></details>

:thinking: 
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 247 at r6](https://reviewable.io/reviews/sillsdev/chorus/223#-MR1HGeAAkDMeryRJfOU:-MR25srG5EiCbIEci5Q8:bqoroxw) ([raw file](https://github.com/sillsdev/chorus/blob/36e91aa6d85285b6ee1dbf4ff3018bd784558181/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L247)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> // TODO ??:Assert.A
> ```
So is this returning Low Bandwidth right now?

</blockquote></details>

"safe mode" is nonresumable, which is recommended for high-bandwidth users. Aren't you glad we're clearing this up?
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 38 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6vyqx1HN-5hh6OKCM:-MR6vyqx1HN-5hh6OKCN:b-g3krj2) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L38)):*
> ```Smalltalk
> 			var newModel = new ServerSettingsModel();
> 			newModel.InitFromUri(urlWithEncodedChars);
> 			// TODO (Hasso) 2020.10: how to test?
> ```

looks like I may still have TODO this
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 115 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6xYmFEGRN5jPPM66S:-MR6xYmFEGRN5jPPM66T:b-pojojo) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L115)):*
> ```Smalltalk
> 			{
> 				Username = "john",
> 				Password = "settings"
> ```

this should really use the settings, not just a partially-initialized model

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: 34 of 40 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 38 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR6vyqx1HN-5hh6OKCM:-MR72QYO8j5S4GTBlhkH:b-4wzuhg) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L38)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

looks like I may still have TODO this
</blockquote></details>

no need to round-trip to a location that intentionally excludes this data

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 9 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/LibChorus/VcsDrivers/RepositoryAddress.cs, line 463 at r10](https://reviewable.io/reviews/sillsdev/chorus/223#-MR76pB_4c2WmxaWtm3C:-MR76pB_4c2WmxaWtm3D:bgdtcvs) ([raw file](https://github.com/sillsdev/chorus/blob/ac08d92bb66e6475fa395cea8767bec66e3a37d5/src/LibChorus/VcsDrivers/RepositoryAddress.cs#L463)):*
> ```
> continue;
> ```

While this is technically a useless statement to the compiler, it saves a human code reader a lot of time.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/223)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
