### PR TITLE
Copy packages to the local nuget repository

### PR DESCRIPTION
**Pull request by papeh**
after packing, if the local nuget repo is specified

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/227)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I think this deserves a mention in the ReadMe

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/227#-:-MOrodUvC3vGeof-wcdm:b-u032xs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Comment by papeh** [comment]
I've updated the Palaso readme; I'll update this one next year.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Review by ermshiperete — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/227#-:-MQLarfz9tnFxzGSkPK9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Pull request merged**
