### PR TITLE
Obscure password in log

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/241)

### CODE REVIEW

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/241)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)

___
*[src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, line 591 at r1](https://reviewable.io/reviews/sillsdev/chorus/241#-MSEQncG8-hdXZvBntxY:-MSEQncHBGsMLbHzo8FB:b8auer1) ([raw file](https://github.com/sillsdev/chorus/blob/a783be7c74dd900faa3eac116ed385bda27543c5/src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs#L591)):*
> ```
> //var 
> ```
:broom:
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 437 at r1](https://reviewable.io/reviews/sillsdev/chorus/241#-MSERigt9znAswqmj0pR:-MSERigt9znAswqmj0pS:b-v66nfl) ([raw file](https://github.com/sillsdev/chorus/blob/a783be7c74dd900faa3eac116ed385bda27543c5/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L437)):*
> ```Smalltalk
> 			Assert.DoesNotThrow(() => ServerSettingsModel.RemovePasswordForLog(string.Empty));
> 		}
> ```

One more test to verify that the a password is not actually in the Log would be good.

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/241)* status: all files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs, line 591 at r1](https://reviewable.io/reviews/sillsdev/chorus/241#-MSEQncG8-hdXZvBntxY:-MSE_rFX5eYIHKypCvIY:bmkp04y) ([raw file](https://github.com/sillsdev/chorus/blob/a783be7c74dd900faa3eac116ed385bda27543c5/src/LibChorus/VcsDrivers/Mercurial/HgRepository.cs#L591)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> //var 
> ```
:broom:
</blockquote></details>

:checkered_flag: 
___
*[src/LibChorusTests/Model/ServerSettingsModelTests.cs, line 437 at r1](https://reviewable.io/reviews/sillsdev/chorus/241#-MSERigt9znAswqmj0pR:-MSE_fV09Hxzj8q3poyT:br5iara) ([raw file](https://github.com/sillsdev/chorus/blob/a783be7c74dd900faa3eac116ed385bda27543c5/src/LibChorusTests/Model/ServerSettingsModelTests.cs#L437)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

One more test to verify that the a password is not actually in the Log would be good. 
</blockquote></details>

here, or in the dozen places where the URL is logged?

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/241)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/241)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
