### PR TITLE
Default to High Bandwidth (simple clone) LanguageForge interface

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/274)

### CODE REVIEW

**Comment by papeh** [comment]
Pending discussion, we may rename these items or simply remove the combobox.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Comment by papeh** [comment]
Waiting to merge until https://jira.sil.org/browse/LT-20639 is resolved

**Comment by papeh** [comment]
can be reopened when https://jira.sil.org/browse/LT-20639 is resolved

**Comment by papeh** [comment]
FLEx Bridge has dropped Linux support (the bug blocking this change is Linux-specific).
Moreover, https://github.com/sillsdev/chorus/pull/305 has changed the default to High bandwidth.

**Pull request closed without merging**
