### PR TITLE
Fix : LT-18380 Chorus build for AnyCPU and 64-bit build

### PR DESCRIPTION
**Pull request by samdoss**
* Modified the project file to support 64bit
  * In buildupdate sh file modified libpalaso

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/133)

### CODE REVIEW

**Comment by papeh** [comment]
Looks good. Unfortunately, I've been away from this project so long that I've forgotten why we need two identical PropertyGroups for AnyCPU and x64.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Chorus/Chorus.csproj, line 50 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/133#-KsG4ThsZZcYp-NKgX1N:-KsG4ThsZZcYp-NKgX1O:b-r3vr33) ([raw file](https://github.com/sillsdev/chorus/blob/2d2bd66d3895f87d25ca99f4eb64600ad68b8297/src/Chorus/Chorus.csproj#L50)):*
> ```XML
>     <UseVSHostingProcess>true</UseVSHostingProcess>
>     <Prefer32Bit>false</Prefer32Bit>
>     <LangVersion>default</LangVersion>
> ```

could you help me understand why this changed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/133#-:-KsG5X7elVKO7YaZIXUc:b-ujf2ng)*

**Comment by samdoss** [comment]
<LangVersion>default</LangVersion>
could you help me understand why this changed?

As we used Visual Studio 2013, and as it gave an error message (Error	1572 Invalid option '6' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default), we changed it to Default.
But now we checked with VS2015, and C# 6.0 was available in it. So we will change it back to 6.

**Comment by samdoss** [comment]
why we need two identical PropertyGroups for AnyCPU and x64.

As we discussed with Jason, It may need AnyCPU and x64.


[8/11/2017 5:16:51 PM] Samdoss: Jason, I have one doubt.
[8/11/2017 5:18:47 PM | Edited 5:19:22 PM] Samdoss: For : if we set to x64 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">

What is the platform target?

<PlatformTarget>AnyCPU or x64</PlatformTarget>

if it set to AnyCPU <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">

What is the platform target?

<PlatformTarget>AnyCPU or x64</PlatformTarget>
[8/11/2017 5:19:32 PM] Jason Naylor: Are you referring to Chorus or FLEx?
[8/11/2017 5:19:42 PM] Samdoss: Chorus
[8/11/2017 5:21:52 PM] Jason Naylor: For Chorus we would prefer to use AnyCPU. The only way that this could cause problems is if Chorus depends on assemblies that have different 32bit and 64bit versions.


Kindly suggest if we need to change anything in the propertygroup.

Thanks & Regards,

Samdoss J

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/133#-:-KswO-xJM_GTSQMoLms8:bs1thl1)*

**Comment by papeh** [comment]
So if we have to have both AnyCPU and x64 builds defined, even if we want to build AnyCPU in both cases, :lgtm:

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/133#-:-KtIIB36Ykw7MHXgNUnv:b9gwq16)*

**Comment by papeh** [comment]
@samdoss, if you'd like to work together to rebase and merge this, ping me when I get in tomorrow.

**Comment by samdoss** [comment]
We are not sure about that, What the build needs whether AnyCPU or x64. If you think its not required in both cases. I can revert my changes and keep one.

and we will work together by tomorrow. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/133#-:-KtvsUNsVH3gJrRn92n8:b31nogm)*

**Comment by samdoss** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Chorus/Chorus.csproj, line 50 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/133#-KsG4ThsZZcYp-NKgX1N:-Ktvu9m1UfNoYa7Z-aiM:b-896fix) ([raw file](https://github.com/sillsdev/chorus/blob/2d2bd66d3895f87d25ca99f4eb64600ad68b8297/src/Chorus/Chorus.csproj#L50)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

could you help me understand why this changed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/133)*

**Comment by papeh** [comment]
(I've also updated the TeamCity build.)

**Pull request merged**
