### PR TITLE
Add property to get GUID of the status message

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/161)

### CODE REVIEW

**Comment by papeh** [comment]
:lgtm: although it may be slightly safer to `LastMessage()?.GetAttributeValue("guid") ?? string.Empty`

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161#-:-L4fzIQZfNtDSm0Nvg20:b-6o37pu)*

**Comment by ermshiperete** [comment]
I agree, but unfortunately this branch still tracks the chorus-2.5 branch which still uses Mono 3.x, so we can't  use C# 6 features.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161#-:-L4g0cKYZOPQyNv4iBat:b-bjdja4)*

**Comment by rmunn** [comment]
Jenkins build is failing on just one test, Chorus.Tests.SyncControlModelTests.AsyncLocalCheckIn_NoHgLockWarningWithMultipleWorkers. The test runs three copies of SyncControlModel.AsyncLocalCheckIn as background workers, and waits one minute before giving up. There's a previous test that runs a single SyncControlModel.AsyncLocalCheckIn, and in the Jenkins build log, that test takes 22 seconds. If the three background workers are competing for resources on a resource-starved system, it's likely that this test would take about 66 seconds to run, so this is a spurious failure that would be solved by bumping the timeout up to, say, 3 minutes:

```diff
diff --git a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs b/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
index 988fc3b..2f63646 100644
--- a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
+++ b/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs
@@ -174,7 +174,7 @@ public void AsyncLocalCheckIn_NoHgLockWarningWithMultipleWorkers()
                        {
                                Thread.Sleep(100);
                                Application.DoEvents();//without this, the background worker starves 'cause their's no UI
-                               if(DateTime.Now.Subtract(start).Minutes > 0)
+                               if(DateTime.Now.Subtract(start).Minutes > 2)
                                {
                                        Assert.Fail("Gave up waiting.");
                                }
```

**Comment by ermshiperete** [comment]
Thanks Robin for analysing the test failure! I did some refactoring but basically increased the timeout to 3 minutes for this test.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161#-:-L4ki78M7xNRPNgrknN3:b-k53vrw)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 124 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4l0eugb09T8Sc-VQGK:-L4l0eugb09T8Sc-VQGL:b-gf89h7) ([raw file](https://github.com/sillsdev/chorus/blob/6f79fd744f1f0ecf8042727a39dcf93e8d34f55a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L124)):*
> ```Smalltalk
> 			SyncResults results = null;
> 			var waitHandle = new AutoResetEvent(false);
> 			_model.SynchronizeOver += (sender, e) => results = (sender as SyncResults);
> ```

no need to `waitHandle.Set()` for the first two tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161#-:-L4l0WIvi1tFmeGuIwzc:bnfp4nl)*

**Comment by ermshiperete** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 124 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4l0eugb09T8Sc-VQGK:-L4lWsYU5z5dp_P1n-gc:b4a1sbz) ([raw file](https://github.com/sillsdev/chorus/blob/6f79fd744f1f0ecf8042727a39dcf93e8d34f55a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L124)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

no need to `waitHandle.Set()` for the first two tests?
</blockquote></details>

No wonder the test fails :smile:  Thanks! But it turns out that even with correctly setting the waitHandle it still doesn't work  - I guess in this case it needs the Application.DoEvents(). So I reverted back to the previous code for this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161)*

**Comment by papeh** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 124 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4l0eugb09T8Sc-VQGK:-L4lvUyG2wdKpUQ8zmy0:bcogw3s) ([raw file](https://github.com/sillsdev/chorus/blob/6f79fd744f1f0ecf8042727a39dcf93e8d34f55a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L124)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

No wonder the test fails :smile:  Thanks! But it turns out that even with correctly setting the waitHandle it still doesn't work  - I guess in this case it needs the Application.DoEvents(). So I reverted back to the previous code for this test.
</blockquote></details>

Could you try calling Application.DoEvents(); before calling WaitForTasksToFinish?

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 107 at r3](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4ltbFlcCLJrrpjXUwX:-L4ltbFlcCLJrrpjXUwY:b-unyh1y) ([raw file](https://github.com/sillsdev/chorus/blob/0c0319c2e97e7905295e0b07a30f23c10919a852/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L107)):*
> ```Smalltalk
> 			SyncResults results = null;
> 			var waitHandle = new AutoResetEvent(false);
> 			_model.SynchronizeOver += (sender, e) => results = (sender as SyncResults);
> ```

no need to call `waitHandle.Set()` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161)*

**Comment by ermshiperete** [comment]
I realized that we don't need the `lfmerge` branch anymore and should work on the `chorus-2.6` branch instead, so I'm closing this PR and creating a new one.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 124 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4l0eugb09T8Sc-VQGK:-L4oVQ8C9R2MSFWVPwwk:bxmmtfm) ([raw file](https://github.com/sillsdev/chorus/blob/6f79fd744f1f0ecf8042727a39dcf93e8d34f55a/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L124)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Could you try calling Application.DoEvents(); before calling WaitForTasksToFinish?
</blockquote></details>

Good idea. Alas, it doesn't work.

---

*[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 107 at r3](https://reviewable.io:443/reviews/sillsdev/chorus/161#-L4ltbFlcCLJrrpjXUwX:-L4ogbzviKvy4QAZhJS6:brfjp9v) ([raw file](https://github.com/sillsdev/chorus/blob/0c0319c2e97e7905295e0b07a30f23c10919a852/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L107)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

no need to call `waitHandle.Set()` here?
</blockquote></details>

Thanks for a careful review! The culprit is the Sync() method that doesn't work without plenty of Application.DoEvents(), so I'll had to revert to the while loop for this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/161#-:-L4ogzAxEJN5dDWnnYCW:bt1p4s4)*

**Comment by ermshiperete** [comment]
Actually, we can't use the chorus-2.6 branch because that uses libpalaso 3.1 which we can't use in lfmerge yet. So I'm reopening this PR.

**Pull request closed without merging**
