### PR TITLE
Merge feature/nuget into master

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 8 of 77 files at r1, 1 of 28 files at r2, 28 of 139 files at r4, 1 of 11 files at r5, 4 of 55 files at r7, 1 of 32 files at r8, 3 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)* status: 46 of 269 files reviewed, 2 unresolved discussions (waiting on @ermshiperete)

___
*[GitVersion.yml, line 6 at r9](https://reviewable.io/reviews/sillsdev/chorus/254#-MZZV7CM1D7WheQdyHuC:-MZZV7CNAKx5045ggGWl:bzavsno) ([raw file](https://github.com/sillsdev/chorus/blob/a0bdff005c1a2fda9c7be20112b55f61715a97e4/GitVersion.yml#L6)):*
> ```
> beta
> ```
We are really releasing from master aren't we, shouldn't this be stable, or something other than beta?
___
*[MercurialExtensions/.guidsForInstaller.xml, line 2 at r9](https://reviewable.io/reviews/sillsdev/chorus/254#-MZZVrFl-ynh1QOM6jM0:-MZZVrFm4RNuvRuymf0L:b-qwf9w4) ([raw file](https://github.com/sillsdev/chorus/blob/97a15e86a196d561ed3691eb45bd42e8dbed6559/MercurialExtensions/.guidsForInstaller.xml#L2)):*
> ```
> 
> ```
This makes me wonder about the Chorus MergeModule that we have been building and using in the past. Any windows installers which relied on this will need to be updated if we have stopped supporting it. (I'm not sure what the status of it is in the feature/nuget branch.)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 7 of 77 files at r1, 12 of 83 files at r3, 15 of 139 files at r4, 10 of 55 files at r7, 5 of 32 files at r8, 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)* status: 96 of 269 files reviewed, 2 unresolved discussions (waiting on @ermshiperete)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 16 of 77 files at r1, 2 of 28 files at r2, 34 of 83 files at r3, 16 of 139 files at r4, 12 of 55 files at r7, 11 of 32 files at r8, 5 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)* status: 192 of 269 files reviewed, 2 unresolved discussions (waiting on @ermshiperete)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 8 of 77 files at r1, 2 of 83 files at r3, 48 of 139 files at r4, 11 of 55 files at r7, 8 of 32 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)* status: all files reviewed, 2 unresolved discussions (waiting on @ermshiperete)

**Comment by bobeaton** [comment]
I use the ChorusMergeModule… are you saying that it is no longer valid?

Bob

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/254)* status: all files reviewed, 2 unresolved discussions (waiting on @bobeaton and @jasonleenaylor)

___
*[GitVersion.yml, line 6 at r9](https://reviewable.io/reviews/sillsdev/chorus/254#-MZZV7CM1D7WheQdyHuC:-MZq_buB4PliruXK7nMN:b-noa5iv) ([raw file](https://github.com/sillsdev/chorus/blob/a0bdff005c1a2fda9c7be20112b55f61715a97e4/GitVersion.yml#L6)):*
> We are really releasing from master aren't we, shouldn't this be stable, or something other than beta?

This depends on what we want. If we want every commit on `master` to be a release and increment the version then yes, this should be something different. As it is right now, every commit on `master` will create a new beta release, and we decide when we want to do a stable release by adding a git tag.
___
*[MercurialExtensions/.guidsForInstaller.xml, line 2 at r9](https://reviewable.io/reviews/sillsdev/chorus/254#-MZZVrFl-ynh1QOM6jM0:-MZqZy3m-n7bdLY8BnCw:bn4c5rd) ([raw file](https://github.com/sillsdev/chorus/blob/97a15e86a196d561ed3691eb45bd42e8dbed6559/MercurialExtensions/.guidsForInstaller.xml#L2)):*
<details><summary><i>Previously, bobeaton wrote…</i></summary><blockquote>



This makes me wonder about the Chorus MergeModule that we have been building and using in the past. Any windows installers which relied on this will need to be updated if we have stopped supporting it. (I'm not sure what the status of it is in the feature/nuget branch.)


</blockquote></details>

Nothing really changed. We're still building the MergeModule. The only difference is that this code now moved to a separate repository (https://github.com/sillsdev/Mercurial4Chorus) that creates a nuget package (SIL.Chorus.Mercurial). Chorus uses this nuget package and still has a build target to create the MergeModule.

**Pull request merged**
