### PR TITLE
Move some new functionality from Flex Bridge to Chorus

### PR DESCRIPTION
**Pull request by regnrand**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/90)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by ermshiperete** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 167 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ0Slviaea-PpwhYeq:-KHQ0Slviaea-PpwhYer:225146783) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L167)):*
> ```Smalltalk
> 		public void UpdateToLongHashOnEmptyRepoReturns_UpdateResults_NoCommitsInRepository()
> 		{
> 			using (var testRoot = new TemporaryFolder("ChorusHgWrappingTest"))
> ```

s/"ChorusHgWrappingTest"/"RepositoryTests"

Not that it matters to much...

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 206 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ0z_8c27kn1ASQ91x:-KHQ0z_8c27kn1ASQ91y:694531060) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L206)):*
> ```Smalltalk
> 							var testRev = repo.GetRevisionWorkingSetIsBasedOn();
> 							// It did move.
> 							Assert.That(file0Rev.Number.LongHash, Is.EqualTo(testRev.Number.LongHash));
> ```

This seems backwards. `testRev` should come first since that's the one we're testing.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 207 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1GpqXwXVg5edrS4W:-KHQ1GpqXwXVg5edrS4X:517156841) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L207)):*
> ```Smalltalk
> 							// It did move.
> 							Assert.That(file0Rev.Number.LongHash, Is.EqualTo(testRev.Number.LongHash));
> 							Assert.That(file0Rev.Branch, Is.EqualTo(string.Empty)); // default branch returns string.Empty in mercurial.
> ```

That should be `testRev.Branch`.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1OI6Ozlt5bF7KLNH:-KHQ1OI6Ozlt5bF7KLNI:-189593077) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L211)):*
> ```Smalltalk
> 							Assert.That(repo.UpdateToLongHash(file2Rev.Number.LongHash), Is.EqualTo(HgRepository.UpdateResults.Success));
> 							testRev = repo.GetRevisionWorkingSetIsBasedOn();
> 							Assert.That(file2Rev.Number.LongHash, Is.EqualTo(testRev.Number.LongHash));
> ```

See above

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 245 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ3KU6o2OD73ucQNXr:-KHQ3KU6o2OD73ucQNXs:1811339445) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L245)):*
> ```Smalltalk
> 							// Set up for another pass to update to file2Rev from file1Rev
> 							// Switch back to rev 2 (newbranch branch), using old method.
> 							// Switch back to rev 2 (newbranch branch), using old method.
> ```

Seems this comment line appeared twice twice.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 367 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ5Pfhn11BZyrKCWx1:-KHQ5Pfhn11BZyrKCWx2:-1288988674) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L367)):*
> ```Smalltalk
> 
> 						// SUT
> 						Assert.That(repo.UpdateToBranchHead(file1Rev.Branch), Is.EqualTo(HgRepository.UpdateResults.Success));
> ```

I'm confused - we're on rev `1` which is on `newbranch`. Before we were on rev `2` also on `newbranch`. Why is this returning `Success` while it returned `AlreadyOnIt` before?

Ahh, I see. We try to switch to the branch head with highest rev. I wonder if this should be reflected in the method name, e.g. `UpdateToHighestBranchHead`? At least a comment in the test here might be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/90)*

**Comment by regnrand** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 167 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ0Slviaea-PpwhYeq:-KHQEYOqHp9BhpG7Vh1q:1583108152) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L167)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> s/"ChorusHgWrappingTest"/"RepositoryTests"
> 
> Not that it matters to much...</details>
Done in all new test cases.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 206 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ0z_8c27kn1ASQ91x:-KHQGQAlPSj2Hpbt2KQU:1238081758) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L206)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> This seems backwards. `testRev` should come first since that's the one we're testing.</details>
Swapped order in all cases to have "testRev.Number.LongHash" be first.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 207 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1GpqXwXVg5edrS4W:-KHQHCsOSG22oSMXrcNM:-499146009) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L207)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> That should be `testRev.Branch`.</details>
Done.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 211 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1OI6Ozlt5bF7KLNH:-KHQHN-JJeOAufexH1hB:-2090868717) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L211)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> See above</details>
If this means that all of the "testRev.Number.LongHash" calls should be first, then all have been changed.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 245 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ3KU6o2OD73ucQNXr:-KHQHfIwyAPEqXRH2o3-:1085144714) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L245)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> Seems this comment line appeared twice twice.</details>
It does look like it. :-( Removed one of them.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 367 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ5Pfhn11BZyrKCWx1:-KHQMZ_RDg5MZW_IRfWD:-2086352564) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L367)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> I'm confused - we're on rev `1` which is on `newbranch`. Before we were on rev `2` also on `newbranch`. Why is this returning `Success` while it returned `AlreadyOnIt` before?
> 
> Ahh, I see. We try to switch to the branch head with highest rev. I wonder if this should be reflected in the method name, e.g. `UpdateToHighestBranchHead`? At least a comment in the test here might be good.</details>
It isn't just that it went to the highest local revision number, but that there are two heads of 'newbranch', and it went to the highest local rev number of one of those two heads. I did add more comments in the test in this area.

I added that in the main method, because it is a possible path through the code, but it would normally never hit that option, since having two heads of the same branch in Chorus is more a pathological state, such as a merge failure. Last I looked (some years back), Chorus does not push such a two headed branch, but keeps it locally.

Practically, speaking, I doubt LF Bridge will run into this, since it is way more interested in getting to the revision of the long hash, without worrying which branch that revision is on. Lf Bridge will only fret about getting the right branch, when it clones a repo and it will then want the highest rev number of any potential two headed branches that come in (again a very low probability, as long as Chorus won't push that to LD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/90)*

**Comment by ermshiperete** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 207 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1GpqXwXVg5edrS4W:-KHQZB01DKp0nzaxdWmN:1941116304) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L207)):*
<details><summary><i>Previously, regnrand (Randy Regnier) wrote…</i></summary>
> Done.</details>
I think you missed this one.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 235 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQZwQsxmoq8Pkzc7xk:-KHQZwQsxmoq8Pkzc7xl:77240662) ([raw file](https://github.com/sillsdev/chorus/blob/07a9051508dddf4ff984a6489ffc49af3966e940/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L235)):*
> ```Smalltalk
> 							// It did move.
> 							Assert.That(testRev.Number.LongHash, Is.EqualTo(file2Rev.Number.LongHash));
> 							Assert.That(file2Rev.Branch, Is.EqualTo("newbranch"));
> ```

should be `testRev.Branch`

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 249 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ_Bbhlu6-R9Ai80Eh:-KHQ_Bbhlu6-R9Ai80Ei:77240662) ([raw file](https://github.com/sillsdev/chorus/blob/07a9051508dddf4ff984a6489ffc49af3966e940/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L249)):*
> ```Smalltalk
> 							// It did move.
> 							Assert.That(testRev.Number.LongHash, Is.EqualTo(file2Rev.Number.LongHash));
> 							Assert.That(file2Rev.Branch, Is.EqualTo("newbranch"));
> ```

should be `testRev.Branch`

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 263 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ_Epsh4ciD2BqkFNL:-KHQ_Epsh4ciD2BqkFNM:77240662) ([raw file](https://github.com/sillsdev/chorus/blob/07a9051508dddf4ff984a6489ffc49af3966e940/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L263)):*
> ```Smalltalk
> 							// It did move.
> 							Assert.That(testRev.Number.LongHash, Is.EqualTo(file1Rev.Number.LongHash));
> 							Assert.That(file1Rev.Branch, Is.EqualTo(string.Empty)); // default branch returns string.Empty in mercurial.
> ```

should be `testRev.Branch`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/90)*

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by regnrand** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs, line 207 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/90#-KHQ1GpqXwXVg5edrS4W:-KHQam2zAfaMh-eqqpb5:-610408174) ([raw file](https://github.com/sillsdev/chorus/blob/b4924b50045bf59c7ce74072fca5156e86f5664d/src/LibChorusTests/VcsDrivers/Mercurial/RepositoryTests.cs#L207)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> I think you missed this one.</details>
Guess I only swapped all of those "testRev.Number.LongHash" ones, not the Branch ones. Those will come in a PR shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/90)*

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by ermshiperete** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/90)*

**Pull request merged**
