### PR TITLE
Make server and internet clone models more UI independent 

### PR DESCRIPTION
**Pull request by ermshiperete**
- move ServerSettingsModel to LibChorus
- add new InternetCloneSettingsModel in LibChorus that has most of
  the previous functionality of GetCloneFromInternetModel but is
  strictly UI independent (it has a progress object, but that is
  UI agnostic)
- derive GetCloneFromInternetModel from InternetCloneSettingsModel
  and wrap a few methods that catch errors and display UI to the
  user.

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/chorus/75)

### CODE REVIEW

**Comment by ermshiperete** [comment]
I'm not totally convinced that it's the best approach to move the entire model classes to LibChorus, so I'd be open for better suggestions :smile:

**Comment by jasonleenaylor** [comment]
<sup>**[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/75#-K2mWSs2LsaVv-Kui7A1)** ([raw file](https://github.com/sillsdev/chorus/blob/61d704ccee4b32b0123d25b6afe0979c298091ab/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L114)):</sup>
Any reason to leave the Category?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/75)

**Comment by jasonleenaylor** [comment]
<sup>**[src/LibChorus/LibChorus.csproj, line 380 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/75#-K2mWjWruKJzILxEnL97)** ([raw file](https://github.com/sillsdev/chorus/blob/61d704ccee4b32b0123d25b6afe0979c298091ab/src/LibChorus/LibChorus.csproj#L380)):</sup>
Aweful lot of whitespace churn here. Is this going to happen again as soon as someone touches this file in Visual Studio?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/75)

**Comment by jasonleenaylor** [comment]
Reviewed 17 of 17 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/75)

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/75#-K2mWSs2LsaVv-Kui7A1)** ([raw file](https://github.com/sillsdev/chorus/blob/61d704ccee4b32b0123d25b6afe0979c298091ab/src/Chorus.Tests/UI/Sync/SyncControlModelTests.cs#L114)):</sup>
Done.


---

<sup>**[src/LibChorus/LibChorus.csproj, line 380 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/75#-K2mWjWruKJzILxEnL97)** ([raw file](https://github.com/sillsdev/chorus/blob/61d704ccee4b32b0123d25b6afe0979c298091ab/src/LibChorus/LibChorus.csproj#L380)):</sup>
Good point, thanks! I didn't pay attention when I added this file. Only the relevant changed lines are included now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/75)

**Pull request merged**
