### PR TITLE
Fix test failures on chorus master build

### PR DESCRIPTION
**Pull request by jasonleenaylor**
Invert the Prefer32bit option

* Prefer32bit for ChorusMerge unless x64 is the Platform

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/146)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ChorusMerge/ChorusMerge.csproj, line 59 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/146#-KyqBLX4RHXsjhtXWAvb:-KyqBLX4RHXsjhtXWAvc:bul8cp9) ([raw file](https://github.com/sillsdev/chorus/blob/2cd91ca9b9be0ab0bd46b75bf70d6b57b778aca3/src/ChorusMerge/ChorusMerge.csproj#L59)):*
> ```XML
>     <WarningLevel>4</WarningLevel>
>     <Optimize>False</Optimize>
>     <Prefer32Bit>false</Prefer32Bit>
> ```

Do Mono AnyCPU builds not need to Prefer32Bit?

---

*[src/ChorusMerge/ChorusMerge.csproj, line 74 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/146#-KyqBbPyhwi_yzSrwqWW:-KyqBbPyhwi_yzSrwqWX:b-7ropln) ([raw file](https://github.com/sillsdev/chorus/blob/2cd91ca9b9be0ab0bd46b75bf70d6b57b778aca3/src/ChorusMerge/ChorusMerge.csproj#L74)):*
> ```XML
>     </TargetFrameworkProfile>
>     <WarningLevel>4</WarningLevel>
>     <Prefer32Bit>false</Prefer32Bit>
> ```

ditto

---

*[src/ChorusMerge.Tests/ChorusMergeTests.cs, line 54 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/146#-KyqC0SFs6sai1D4hPPU:-KyqC0SFs6sai1D4hPPV:b1w04ak) ([raw file](https://github.com/sillsdev/chorus/blob/2cd91ca9b9be0ab0bd46b75bf70d6b57b778aca3/src/ChorusMerge.Tests/ChorusMergeTests.cs#L54)):*
> ```Smalltalk
> 			MergeSituation.PushRevisionsToEnvironmentVariables("bob", "-123", "sally", "-456");
> 			MergeOrder.PushToEnvironmentVariables(group.Folder.Path);
> 			Program.ErrorWriter = Console.Out;
> ```

this would be a good place for a comment such as // we expect this will write errors to the console, which may cause the build fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/146)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ChorusMerge/ChorusMerge.csproj, line 59 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/146#-KyqBLX4RHXsjhtXWAvb:-KyqHXinPDicRR4-o3lh:b-2644x7) ([raw file](https://github.com/sillsdev/chorus/blob/2cd91ca9b9be0ab0bd46b75bf70d6b57b778aca3/src/ChorusMerge/ChorusMerge.csproj#L59)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Do Mono AnyCPU builds not need to Prefer32Bit?
</blockquote></details>

From what I can tell it isn't imortant to Mono. The tests seem happy there, so either this is ignored, or handled different on the Mono build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/146)*

**Comment by jasonleenaylor** [comment]
*[src/ChorusMerge/ChorusMerge.csproj, line 74 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/146#-KyqBbPyhwi_yzSrwqWW:-KyqIkOfVXESPcRoYkJB:b-7ropln) ([raw file](https://github.com/sillsdev/chorus/blob/2cd91ca9b9be0ab0bd46b75bf70d6b57b778aca3/src/ChorusMerge/ChorusMerge.csproj#L74)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/146)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/146#-:-KyqLf6yCjZR47nKnQAC:bnfp4nl)*

**Pull request merged**
