### PR TITLE
Use Autofac from nuget package

### PR DESCRIPTION
**Pull request by ermshiperete**
This makes it easier to see which version of autofac we're using
and where it came from, and it also removes the binary from the repo.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/89)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by sillsdevgerrit** [comment]
Build finished.

**Comment by regnrand** [comment]
Who needs to know the version of Autofac that Chorus is using and why do they need to know it? Chorus would really prefer to dump Autofac overboard and use MEF, but MEF 1 wasn't able to do what needed to be done at the time we wanted to get rid of Autofac. MEF 2 might be up to it by now.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/89#-:-KFtH8iEVItoMHpQQDDk:-603376915)*

**Comment by ermshiperete** [comment]
OK, I retract this change

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/89#-:-KFtWZVRYMyLH4qwyMH1:-1498915129)*

**Pull request closed without merging**
