### PR TITLE
Update L10NSharp to match Palaso

### PR DESCRIPTION
**Pull request by papeh**
Part of https://jira.sil.org/browse/LT-20973 and https://jira.sil.org/browse/LT-20978

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/276)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[src/Chorus/Chorus.csproj, line 13 at r1](https://reviewable.io/reviews/sillsdev/chorus/276#-Mx5ZAI80tb-OPdDKOkC:-Mx5ZAI80tb-OPdDKOkD:bklsxy2) ([raw file](https://github.com/sillsdev/chorus/blob/f5307864192ce823d059d93e072a0ef73e1abaa1/src/Chorus/Chorus.csproj#L13)):*
> ```XML
>     <PackageReference Include="Autofac" Version="2.6.3.862" />
>     <PackageReference Include="GitVersion.MsBuild" Version="5.6.8" PrivateAssets="All" />
>     <PackageReference Include="L10NSharp" Version="5.0.0-beta0059" />
> ```

any reason not to use -* here?



_Code quote:_
```XML
beta0059
```

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/276)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/Chorus/Chorus.csproj, line 13 at r1](https://reviewable.io/reviews/sillsdev/chorus/276#-Mx5ZAI80tb-OPdDKOkC:-Mx5bzLHBqY-IOZybK49:b8v134i) ([raw file](https://github.com/sillsdev/chorus/blob/f5307864192ce823d059d93e072a0ef73e1abaa1/src/Chorus/Chorus.csproj#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

any reason not to use -* here?
</blockquote></details>

Palaso includes the full version. I understand it would still find any newer version, to an extent, but I can put the * back if you'd like.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/276)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

___
*[src/Chorus/Chorus.csproj, line 13 at r1](https://reviewable.io/reviews/sillsdev/chorus/276#-Mx5ZAI80tb-OPdDKOkC:-Mx5tjxGDvKz8qGGhIDe:b-xf8u32) ([raw file](https://github.com/sillsdev/chorus/blob/f5307864192ce823d059d93e072a0ef73e1abaa1/src/Chorus/Chorus.csproj#L13)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Palaso includes the full version. I understand it would still find any newer version, to an extent, but I can put the * back if you'd like.
</blockquote></details>

What happens if we remove this packageref altogether?
In theory it could pick it up from SIL.Windows.Forms.
Since SIL.Windows.Forms isn't tied to a specific version here I wonder if we will end up updating this whenever Palaso builds against a new version.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm_strong: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/276#-:-Mx5vn6M8EJ6Lpd6b4Gv:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/chorus/276)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[src/Chorus/Chorus.csproj, line 13 at r1](https://reviewable.io/reviews/sillsdev/chorus/276#-Mx5ZAI80tb-OPdDKOkC:-Mx5xIVP65ls2e_SaCaN:b-avin3f) ([raw file](https://github.com/sillsdev/chorus/blob/f5307864192ce823d059d93e072a0ef73e1abaa1/src/Chorus/Chorus.csproj#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

What happens if we remove this packageref altogether?
In theory it could pick it up from SIL.Windows.Forms.
Since SIL.Windows.Forms isn't tied to a specific version here I wonder if we will end up updating this whenever Palaso builds against a new version.
</blockquote></details>

That won't work for LibChorus, though, since it doesn't have any WinForms deps.

**Pull request merged**
