### PR TITLE
Use MEF for FileTypeHandlers and EmbeddedMessageContentHandlers

### PR DESCRIPTION
**Pull request by ermshiperete**
These changes are necessary for a change in FlexBridge (https://github.com/sillsdev/flexbridge/pull/64), necessary to implement S/R in LanguageForge.

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/chorus/79)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
I think the commit comments related to MEF are a little sparse. Some acknowledgement of the reason why this change was a good idea would be helpful. Otherwise I can't see any issues with the commit.

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/79#-:-K3QZcRxw1KoII-ssu6F:1718425348)_

**Comment by regnrand** [comment]
Jason, I added this comment a long time ago about a better way to get those handlers:

"This will eventually done using MEF or some other dynamic way of finding available HandlersList"

Looks like it is being done.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/79#-:-K3Qah1lJ28u4N-uGNVB:-2037027400)_

**Comment by ermshiperete** [comment]
Ahh - that was the reason why I did it :smiley:. I did that back in June before I got pulled into fixing FW keyboarding bugs, so I don't remember all the details :smiley:.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/79#-:-K3QcmpqaUXvtfxILyqw:-1260713036)_

**Comment by regnrand** [comment]
You'll get extra credit for replacing all use of "Autofac" in Chorus in favor of MEF. You may need to upgrade to .Net 4.5.1 to be able to pull it off, however. That change to MEF has been 'pre-approved' by JohnH way back, but MEF was not able to do it back then.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/chorus/79#-:-K3QkEhp5sidkHPfhOtU:-2033939369)_

**Comment by jasonleenaylor** [comment]
Ok, LGTM

**Comment by jasonleenaylor** [comment]
I suppose WeSay has no necessary changes, or does it have TypeHandlers of its own for configuration files?

**Comment by regnrand** [comment]
WeSay uses the handlers in Chorus.

Randy

**Pull request merged**
