### PR TITLE
PTX-41359 add API methods required for support PTX send/receive requirements

### PR DESCRIPTION
**Pull request by jwickberg**
There are no changes to existing API methods.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/94)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/LibChorus/ChorusHub/IChorusHubService.cs, line 96 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/94#-KJv_VXTPPIT9BP4UQCz:-KJv_VXTPPIT9BP4UQD-:1927726083) ([raw file](https://github.com/sillsdev/chorus/blob/35a3ccdb40995d0adaf912abf3252471cb9af185/src/LibChorus/ChorusHub/IChorusHubService.cs#L96)):*
> ```Smalltalk
> 		/// </summary>
> 		[OperationContract]
> 		void PutFileFromText(string folder, string fileName, string contents);
> ```

Could you update the summary of these Put/Get file methods to include a brief explanation of their expected use?
(I presume it is to support files that are not a part of the hg repository but that need to be transferred between users)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/94)*

**Comment by jwickberg** [comment]
Added some comments and updated the commit.

**Comment by jasonleenaylor** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/LibChorus/ChorusHub/IChorusHubService.cs, line 96 \[r1\]](https://reviewable.io:443/reviews/sillsdev/chorus/94#-KJv_VXTPPIT9BP4UQCz:-KJvsMz60GFR6qzDSQqj:5174689) ([raw file](https://github.com/sillsdev/chorus/blob/35a3ccdb40995d0adaf912abf3252471cb9af185/src/LibChorus/ChorusHub/IChorusHubService.cs#L96)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary>
> Could you update the summary of these Put/Get file methods to include a brief explanation of their expected use?
> (I presume it is to support files that are not a part of the hg repository but that need to be transferred between users)
</details>
ok

---

*[src/LibChorus/ChorusHub/IChorusHubService.cs, line 95 \[r2\]](https://reviewable.io:443/reviews/sillsdev/chorus/94#-KJvs2hyds85bT95vMqk:-KJvs2hyds85bT95vMql:-458952) ([raw file](https://github.com/sillsdev/chorus/blob/6bedcbb5d7f54a04269ecf6445ff1f1f168508f7/src/LibChorus/ChorusHub/IChorusHubService.cs#L95)):*
> ```Smalltalk
> 		/// exist.
>         ///
>         /// Used for sharing files that are not part of a project. One example is a per user file that
> ```

I think you used tabs originally and spaces for the addition. Could you fix that up? :-/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/94)*

**Comment by jwickberg** [comment]
Changed all leading spaces to tabs.

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/94#-:-KKJhX1CEhoOc9GE3lAi:1417088721)*

**Pull request merged**
