### PR TITLE
Languagedepot SSL

### PR DESCRIPTION
**Pull request by megahirt**
This PR adds 3 new HTTPS entries into the server list in the Chorus Settings dialog:

- resumable [secure]
- private [secure + safe mode]
- public [secure + safe mode]

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/chorus/107)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/LibChorus/Model/ServerSettingsModel.cs, line 38 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWl46zrmEA9-I5kSvdn:-KWl46zrmEA9-I5kSvdo:b-sq7r5a) ([raw file](https://github.com/sillsdev/chorus/blob/e11b62397422cf0a1ffa349ca65128f295fff7ca/src/LibChorus/Model/ServerSettingsModel.cs#L38)):*
> ```Smalltalk
> 			Servers.Add(languageDepotLabel, new ServerModel("resumable.languagedepot.org", false));
> 			Servers.Add(languageDepotLabel + " [Secure]", new ServerModel("resumable.languagedepot.org"));
> 			Servers.Add("LanguageDepot.org [Safe Mode]", new ServerModel("hg-public.languagedepot.org", false));
> ```

I wonder why we use the hard-coded inline "LanguageDepot.org" string here but the `languageDepotLabel` variable in the two lines above.

---

*[src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs, line 465 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWl6HTj527fuWBPA_tN:-KWl6HTj527fuWBPA_tO:bg5yjmc) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs#L465)):*
> ```Smalltalk
> 				e.LocalAddAndCommitLargeFile();
> 				var serverMessage = "The server is down for scheduled maintenance";
> 				e.ApiServer.AddServerUnavailableResponse(2, serverMessage);
> ```

I wonder why you changed this number? I didn't look carefully at the test and the environment, but a quick look suggests that the number simulates a server failure at different points in the s/r process. We pass 2 to `AddServerUnavailableResponse` in a test below, so I wonder if this should remain 4?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
*[src/LibChorus/Model/ServerSettingsModel.cs, line 38 at r1](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWl46zrmEA9-I5kSvdn:-KWl9X5J1gbjff5Rqaud:bs0pdvp) ([raw file](https://github.com/sillsdev/chorus/blob/e11b62397422cf0a1ffa349ca65128f295fff7ca/src/LibChorus/Model/ServerSettingsModel.cs#L38)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> I wonder why we use the hard-coded inline "LanguageDepot.org" string here but the `languageDepotLabel` variable in the two lines above.
</details>
The text is in a variable only to set the SelectedServerlabel at the bottom of the constructor.  No other reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
*[src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs, line 465 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWl6HTj527fuWBPA_tN:-KWlABADfLzuYcyDZNMc:b-olp9i8) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorusTests/VcsDrivers/Mercurial/HgResumeTransportTests.cs#L465)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> I wonder why you changed this number? I didn't look carefully at the test and the environment, but a quick look suggests that the number simulates a server failure at different points in the s/r process. We pass 2 to `AddServerUnavailableResponse` in a test below, so I wonder if this should remain 4?
</details>
I noticed that this test was failing after I changed the maximumChunkSize to be 20MB from 250KB.  The algorithm for determining the newChunkSize on the client is based upon the response time.  Because the test runs locally the push happens almost instantly and so the newChunkSize hits the maximum size very quickly (probably on the next request).  In the old code, the max was 250KB and because this test tests on a sufficiently large repo (over 1MB) the test could simulate an unavailable response on the fourth response and it would still be in the middle of a transfer.  With the max chunk size raised to 20MB, the chunkSize gets raised to 20MB probably on the 2nd request and so the transfer is completed on the second response.  It never gets to the 4th API request/response.  So I changed it to 2, since that's still technically mid-transfer.  If I were to check-in a very large test repo, say 100MB, then we could leave this number at 4 and it would still pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107#-:-KWlPs9-uJsPMy6GTse_:bnfp4nl)*

**Comment by cambell-prince** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs, line 34 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWmcCx7JRcztOiZvdK-:-KWmcCx7JRcztOiZvdK0:bi8dzkx) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs#L34)):*
> ```Smalltalk
> 		private const int MaximumChunkSize = 20000000;
> 		private const int TimeoutInSeconds = 30;
> 		private const int TargetTimeInSeconds = 5;
> ```

Based on server observations I would like to see the TargetTimeInSeconds increase to 7. I think that 5 allows for an appropriate delivery time based on bandwidth, but does not sufficiently take into account the server processing time which is not negligible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
*[src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs, line 34 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWmcCx7JRcztOiZvdK-:-KWpAHoToQ2VO8ELyT0X:b-n0ul6v) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs#L34)):*
<details><summary><i>Previously, cambell-prince (Cambell) wrote…</i></summary>
> Based on server observations I would like to see the TargetTimeInSeconds increase to 7. I think that 5 allows for an appropriate delivery time based on bandwidth, but does not sufficiently take into account the server processing time which is not negligible.
</details>
Yes, agreed.  I can change the TargetTimeInSeconds to 7, but that value is only used in determining the newChunkSize, and I felt that it was unnecessary to change the TargetTimeInSeconds since I increased the MaximumChunkSize to allow for fast connections.  The TimeoutInSeconds is the value that we need to change to accommodate server processing time, and I doubled this number from 15 to 30.  Is this sufficient or do you still want to change the TargetTime to 7 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by cambell-prince** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs, line 34 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWmcCx7JRcztOiZvdK-:-KWqrHPwSXj0MBIB0V_f:bgjwopx) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs#L34)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary>
> Yes, agreed.  I can change the TargetTimeInSeconds to 7, but that value is only used in determining the newChunkSize, and I felt that it was unnecessary to change the TargetTimeInSeconds since I increased the MaximumChunkSize to allow for fast connections.  The TimeoutInSeconds is the value that we need to change to accommodate server processing time, and I doubled this number from 15 to 30.  Is this sufficient or do you still want to change the TargetTime to 7 ?
</details>
The TargetTimeInSeconds is used in the calculation based on time since last send.  Often we are seeing connections with good bandwidth (I suspect) that cannot turn around inside the 5 seconds.  Thus they stay at 5K chunks.  Increasing this will give them a chance to head towards their maximum, rather than staying at 5K unnecessarily.  So, yes, 7 would be a beneficial change I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
*[src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs, line 34 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWmcCx7JRcztOiZvdK-:-KX3Y8lL0im75tj2oWGv:b-yagk0y) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs#L34)):*
<details><summary><i>Previously, cambell-prince (Cambell) wrote…</i></summary>
> The TargetTimeInSeconds is used in the calculation based on time since last send.  Often we are seeing connections with good bandwidth (I suspect) that cannot turn around inside the 5 seconds.  Thus they stay at 5K chunks.  Increasing this will give them a chance to head towards their maximum, rather than staying at 5K unnecessarily.  So, yes, 7 would be a beneficial change I think.
</details>
OK Yes, I forgot about that scenario where clients were stuck at 5K per request.  I have increased the target time to 7 seconds.  Hopefully that will help in that situation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
I'm going to force push this branch so that the ONLY change for this PR is the change to HTTPS in the dialog.  This PR unfortunately got stalled because of test failures and I'm attempting to clean them up now.

**Comment by megahirt** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Comment by megahirt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs, line 34 at r2](https://reviewable.io:443/reviews/sillsdev/chorus/107#-KWmcCx7JRcztOiZvdK-:-KimlG-osxwMiCI9kLsu:b1d6i07) ([raw file](https://github.com/sillsdev/chorus/blob/7098dfdc2d0d489bc28562f602b549be6953d256/src/LibChorus/VcsDrivers/Mercurial/HgResumeTransport.cs#L34)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

OK Yes, I forgot about that scenario where clients were stuck at 5K per request.  I have increased the target time to 7 seconds.  Hopefully that will help in that situation.
</blockquote></details>

This comment is relevant for a different PR, the one in which we increase the target time to 7 seconds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/chorus/107)*

**Pull request merged**
